---

- name: Retrieve fstab before patching
  shell:
    cmd: cat /etc/fstab |
        grep -v "#"
    warn: false
  register: fstab_before

- name: Create fstab list before patching
  copy:
    dest: "{{ fstab_list_before }}"
    content: "{{ fstab_before.stdout_lines | join('\n') }}"