---

- name: Retrieve list of mounts before patching
  shell:
    cmd: df -Th |
        grep -v tmpfs |
        awk '{print $1" "$2" "$7}' |
        column -t
    warn: false
  register: mount_before

- name: Create list of mounts before patching
  copy:
    dest: "{{ mount_list_before }}"
    content: "{{ mount_before.stdout_lines | join('\n') }}"