---

- name: Retrieve SELinux status before patching
  shell: sestatus
  register: sestatus_before

- name: Create list of selinux status before patching
  copy:
    dest: "{{ selinux_status_before }}"
    content: "{{ sestatus_before.stdout_lines | join('\n') }}"