---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  vars_prompt:
    - name: package_name
      prompt: Enter the Package name
      private: no

  tasks:

    - name: "Check if package is installed or not"
      shell: 
        cmd: rpm -qa | grep "{{ package_name }}"
        warn: false
      register: package_check
      changed_when: false 
      failed_when: false
    
    - debug:
        msg: "Package not installed"
      when: package_check.stdout == ""
        
    - pause:
        prompt: Do you want to install the package (y/n) ?
        echo: true
      register: action
      run_once: true

    - name: "Install package"
      yum:
        name: "{{ package_name }}"
        state: present
      when: action.user_input|lower == 'y'