---

- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  gather_facts: no

  tasks:

    - name: Fetch DB credentials
      include_vars:
        file: /root/.ansible/secret.yml

    - name: Retrieve list of databases before reboot
      shell: "mysql -u {{ user }} -p{{ pass }} -e 'SHOW DATABASES;'"
      register: result_before

    - name: Store the list of databases in a variable
      set_fact:
        mysql_databases_before: "{{ result_before.stdout_lines[1:] }}"

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the system
      reboot:

    - name: Wait for the system to come back online
      wait_for_connection:

    - name: Retrieve list of databases after reboot
      shell: "mysql -u {{ user }} -p{{ pass }} -e 'SHOW DATABASES;'"
      register: result_after

    - name: Store the list of databases in a variable
      set_fact:
        mysql_databases_after: "{{ result_after.stdout_lines[1:] }}"

    - debug:
        msg: "DB List matched, no changes found"
      when: mysql_databases_before == mysql_databases_after

    - debug:
        msg:
          - "The list of databases has changed after the reboot"
          - "Before reboot: {{ result_before }}"
          - "After reboot: {{ result_after }}"
      when: mysql_databases_before != mysql_databases_after