---

- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  gather_facts: no

  tasks:

    - name: Check pmon services before reboot
      shell: ps -e -o cmd |
            grep pmon |
            grep -v grep
      changed_when: false
      failed_when: false
      register: pmon_before

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Check pmon status after reboot
      shell: ps -e -o cmd |
            grep pmon |
            grep -v grep
      changed_when: false
      failed_when: false
      register: pmon_after

    - debug:
        msg:
          - "All pmon services are up & running"
          - "{{ pmon_after.stdout_lines }}"
      when: pmon_before.stdout == pmon_after.stdout
    
    - debug:
        msg:
          - "pmon services are not running"
          - "{{ pmon_after.stdout_lines }}"
      when: pmon_before.stdout != pmon_after.stdout