---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent
    before: "/tmp/fstab_before_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    after: "/tmp/fstab_after_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    fstab: "./reports/fstab_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"

  tasks:

    - name: Retrieve Packages list before patching
      shell:
        cmd: cat /etc/fstab |
            grep -v "#"
        warn: false
      register: fstab_before
    
    - name: Create list of packages before patching
      copy:
        dest: "{{ before }}"
        content: "{{ fstab_before.stdout_lines | join('\n') }}" 

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Retrieve Packages list after patching
      shell: 
        cmd: cat /etc/fstab |
            grep -v "#"
        warn: false
      register: fstab_after

    - name: Create list of packages after patching
      copy:
        dest: "{{ after }}"
        content: "{{ fstab_after.stdout_lines | join('\n') }}" 
        
    - name: Compare package list before and after patching
      shell: diff "{{ after }}" "{{ before }}" |
            grep -v "^---" |
            grep -v "^[0-9c0-9]"
      register: fstab_diff
      changed_when: fstab_diff != ""
      failed_when: false
    
    - name: Generate Package comparison list
      copy:
        dest: "{{ fstab }}"
        content: "{{ fstab_diff.stdout_lines | join('\n') }}"
      delegate_to: localhost
      when: fstab_before.stdout_lines != fstab_after.stdout_lines