---

- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  tasks:

    - set_fact:
        premounts: "{{ ansible_mounts|count }}"

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot server
      ansible.builtin.reboot:
        reboot_timeout: 3600
        test_command: uptime
    
    - name: Gather facts after patching
      setup:
    
    - set_fact:
        postmounts: "{{ ansible_mounts|count }}"
    
    - assert:
        that:
        - premounts == postmounts
        fail_msg: "Premounts: {{ premounts }} and Postmounts: {{ postmounts }} do not match!"
        success_msg: "Mounts match"