---

- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  tasks:

    - set_fact:
        premounts: "{{ ansible_mounts|count }}"

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot server
      reboot:

    - name: Wait for the system to come back online
      wait_for_connection:

    - name: Gather facts after patching
      setup:
    
    - set_fact:
        postmounts: "{{ ansible_mounts|count }}"
    
    - assert:
        that:
        - premounts == postmounts
        fail_msg: "Premounts: {{ premounts }} and Postmounts: {{ postmounts }} do not match!"
        success_msg: "Mounts match"