---

- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  tasks:

    - set_fact:
        premounts: "{{ ansible_mounts | map(attribute='mount') | list }}"

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Gather facts after patching
      setup:
    
    - set_fact:
        postmounts: "{{ ansible_mounts | map(attribute='mount') | list }}"
    
    - assert:
        that:
        - premounts == postmounts
        fail_msg: "Premounts: {{ premounts }} and Postmounts: {{ postmounts }} do not match!"
        success_msg: "Mounts matched after reboot"