---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent
    pkg_list_before: "/tmp/pkg_before_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    pkg_list_after: "/tmp/pkg_after_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    pkg_list_patched: "./reports/patched_packages_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"

  tasks:

    - name: Retrieve Packages list before patching
      shell:
        cmd: rpm -qa --last |
            sort
        warn: false
      register: pkg_before
    
    - name: Create list of packages before patching
      copy:
        dest: "{{ pkg_list_before }}"
        content: "{{ pkg_before.stdout_lines | join('\n') }}" 

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Retrieve Packages list after patching
      shell:
        cmd: rpm -qa --last |
            sort
        warn: false
      register: pkg_after

    - name: Create list of packages after patching
      copy:
        dest: "{{ pkg_list_after }}"
        content: "{{ pkg_after.stdout_lines | join('\n') }}" 
        
    - name: Compare package list before and after patching
      shell: diff "{{ pkg_list_after }}" "{{ pkg_list_before }}" |
            grep -v "^---" |
            grep -v "^[0-9c0-9]"
      register: pkg_diff
      changed_when: pkg_diff != ""
      failed_when: false
    
    - name: Generate Package comparison list
      copy:
        dest: "{{ pkg_list_patched }}"
        content: "{{ pkg_diff.stdout_lines | join('\n') }}"
      delegate_to: localhost
      when: pkg_before.stdout_lines != pkg_after.stdout_lines