---
- hosts: all
  gather_facts: yes
  become: yes
  vars_files: vars.yml

  vars:
    ansible_python_interpreter: auto_legacy_silent

  tasks:

    - include_role:
        name: pre_patching
    
    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime
    
    - include_role:
        name: post_patching