---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  vars_prompt:
    - name: package_name
      prompt: Enter the Package name
      private: no

  tasks:

    - name: "Extract given package version"
      shell:
        cmd: echo '{{ package_name }}' | egrep -o '[0-9].*-[0-9]'
      register: package_version
    
    - set_fact:
        package_ver: "{{ package_version | regex_replace('\\.', '') | regex_replace('\\-', '') }}"
        
    - name: "Check if package is installed or not"
      shell: 
        cmd: rpm -qa | grep "{{ package_name }}" | egrep -o '[0-9].*-[0-9]'
        warn: false
      register: package_check
      changed_when: false 
      failed_when: false
    
    - set_fact:
        package_chk: "{{ package_check | regex_replace('\\.', '') | regex_replace('\\-', '') }}"

    - name: "Print execution results when same package version installed"
      debug:
        msg: "Package {{ package_name }} is installed"
      when: package_chk.stdout == package_ver.stdout
    
    - name: "Print execution results when package version not matched/installed"
      debug:
        msg: "Package {{ package_name }} is not installed"
      when: package_chk.stdout == ""
    
    - name: "Remove old hostlist"
      file:
        path: ./hostlist
        state: absent
      delegate_to: localhost

    - name: "Create list of hosts with package not matched/installed"
      lineinfile:
        line: "{{ ansible_hostname }}"
        dest: ./hostlist
        create: true
      delegate_to: localhost
      when: package_chk.stdout == ""