---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  vars_prompt:
    - name: package_name
      prompt: Enter the Package name
      private: no

  tasks:

    - name: "Extract package name"
      shell:
        cmd: "yum info '{{ package_name }}' |
              grep -i name |
              awk -F ': ' '{print $2}'"
        warn: false
      register: pkg_name

    - name: "Check if package is installed or not"
      shell: 
        cmd: rpm -q "{{ pkg_name.stdout }}"
        warn: false
      register: package_check
      changed_when: false 
      failed_when: false
    
    - name: "Extract given package version"
      shell:
        cmd: "echo '{{ package_name }}' | egrep -o '[0-9].*-[0-9]'"
        warn: false
      register: package_version
    
    - name: "Extract installed package version"
      shell:
        cmd: "echo '{{ package_check.stdout }}' | egrep -o '[0-9].*-[0-9]'"
        warn: false
      register: package_check_version
      when: '"not installed" not in package_check.stdout'
    
    - pause:
        prompt: |
          Choose an option:
          =================
          1. Install
          2. Upgrade
          3. Remove
      register: action
    
    - set_fact:
        action_var: "{{ action.user_input }}"

    - name: "Install package"
      shell:
        cmd: yum install -y "{{ package_name }}"
        warn: false
      become: yes
      async: 300
      poll: 5
      when:
        - action_var == "1"
        - '"not installed" in package_check.stdout'

    - name: "Update package"
      shell:
        cmd: yum update -y "{{ pkg_name.stdout }}"
        warn: false
      become: yes
      async: 300
      poll: 5
      when:
        - action_var == "2"
        - package_version.stdout > package_check_version.stdout

    - name: "Remove package"
      shell:
        cmd: yum remove -y "{{ pkg_name.stdout }}"
        warn: false
      become: yes
      async: 300
      poll: 5
      when: 
        - action_var == "3"
        - package_version.stdout < package_check_version.stdout