---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent

  tasks:

    - name: Check SELinux status before reboot
      shell: sestatus
      register: selinux_status_before
    
    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Retrieve Packages list after patching
      shell: sestatus
      register: selinux_status_after

    - name: Display SELinux status before and after reboot
      debug:
        msg:
          - "SELinux status before reboot: {{ selinux_status_before.stdout }}"
          - "SELinux status after reboot: {{ selinux_status_after.stdout }}"