---

- name: Retrieve fstab after patching
  shell: 
    cmd: cat /etc/fstab |
        grep -v "#"
    warn: false
  register: fstab_after

- name: Create fstab list after patching
  copy:
    dest: "{{ fstab_list_after }}"
    content: "{{ fstab_after.stdout_lines | join('\n') }}"
    
- name: Compare fstab list before and after patching
  shell: diff "{{ fstab_list_after }}" "{{ fstab_list_before }}" |
        grep -v "^---" |
        grep -v "^[0-9c0-9]"
  register: fstab_diff
  changed_when: fstab_diff != ""
  failed_when: false

- name: Generate fstab comparison list
  copy:
    dest: "{{ fstab_list_compare }}"
    content: "{{ fstab_diff.stdout_lines | join('\n') }}"
  delegate_to: localhost
  when: fstab_before.stdout_lines != fstab_after.stdout_lines