---

- name: Retrieve Packages list after patching
  shell:
    cmd: rpm -qa --last |
        sort
    warn: false
  register: pkg_after

- name: Create list of packages after patching
  copy:
    dest: "{{ pkg_list_after }}"
    content: "{{ pkg_after.stdout_lines | join('\n') }}" 
    
- name: Compare package list before and after patching
  shell: diff "{{ pkg_list_after }}" "{{ pkg_list_before }}" |
        grep -v "^---" |
        grep -v "^[0-9c0-9]"
  register: pkg_diff
  changed_when: pkg_diff != ""
  failed_when: false

- name: Generate Package comparison list
  copy:
    dest: "{{ pkg_list_patched }}"
    content: "{{ pkg_diff.stdout_lines | join('\n') }}"
  delegate_to: localhost
  when: pkg_before.stdout_lines != pkg_after.stdout_lines