---

- name: Retrieve selinux status after patching
  shell: sestatus
  register: sestatus_after

- name: Create list of selinux status after patching
  copy:
    dest: "{{ selinux_status_after }}"
    content: "{{ sestatus_after.stdout_lines | join('\n') }}"

- name: Compare selinux status before and after patching
  shell: diff "{{ selinux_status_after }}" "{{ selinux_status_before }}" |
        grep -v "^---" |
        grep -v "^[0-9c0-9]"
  register: sestatus_diff
  changed_when: sestatus_diff != ""
  failed_when: false

- name: Generate selinux status comparison list
  copy:
    dest: "{{ selinux_status_diff }}"
    content: "{{ sestatus_diff.stdout_lines | join('\n') }}"
  delegate_to: localhost
  when: sestatus_before.stdout_lines != sestatus_after.stdout_lines