---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent
    filename: "./inventory_{{ ansible_date_time.date }}.csv"

  tasks:

    - name: Retrieve Product Name
      shell: 'dmidecode | grep "Product Name" | head -1 | cut -d: -f 2'
      register: product_name
    
    - name: Retrieve Subscription Name
      shell: 'subscription-manager list --consumed | grep "Subscription Name" | cut -d: -f 2'
      register: subscription_name

    - name: Retrieve Entitlement Type
      shell: 'subscription-manager list --consumed | grep "Entitlement Type\|System Type" | cut -d: -f 2'
      register: entitlement_type
    
    - set_fact:
        product: "{{ product_name.stdout|regex_replace('\t', '')|trim }}"
    
    - set_fact:
        subscription: "{{ subscription_name.stdout|trim|regex_replace(',', '') }}"
      when: "',' in subscription_name.stdout"

    - set_fact:
        subscription: "{{ subscription_name.stdout|trim }}"
      when: "',' not in subscription_name.stdout"
    
    - set_fact:
        entitlement: "{{ entitlement_type.stdout|trim }}"

    - name: "Set header"
      shell: echo 'Hostname,IP_Address,Distribution,Product_Name,Subscription_Name,Entitlement_Type' > "{{ filename }}"
      run_once: true
      delegate_to: localhost

    - name: "Write data to file same package version installed"
      shell: echo "{{ ansible_hostname }}","{{ ansible_default_ipv4.address }}","{{ ansible_distribution }} {{ ansible_distribution_version }}","{{ product }}","{{ subscription }}","{{ entitlement }}" >> "{{ filename }}"
      delegate_to: localhost