---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent
    fstab_list_before: "/tmp/fstab_before_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    fstab_list_after: "/tmp/fstab_after_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    fstab_list_compare: "./reports/fstab_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"

  tasks:

    - name: Retrieve fstab before patching
      shell:
        cmd: cat /etc/fstab |
            grep -v "#"
        warn: false
      register: fstab_before
    
    - name: Create fstab list before patching
      copy:
        dest: "{{ fstab_list_before }}"
        content: "{{ fstab_before.stdout_lines | join('\n') }}" 

    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Retrieve fstab after patching
      shell: 
        cmd: cat /etc/fstab |
            grep -v "#"
        warn: false
      register: fstab_after

    - name: Create fstab list after patching
      copy:
        dest: "{{ fstab_list_after }}"
        content: "{{ fstab_after.stdout_lines | join('\n') }}" 
        
    - name: Compare fstab list before and after patching
      shell: diff "{{ fstab_list_after }}" "{{ fstab_list_before }}" |
            grep -v "^---" |
            grep -v "^[0-9c0-9]"
      register: fstab_diff
      changed_when: fstab_diff != ""
      failed_when: false
    
    - name: Generate fstab comparison list
      copy:
        dest: "{{ fstab_list_compare }}"
        content: "{{ fstab_diff.stdout_lines | join('\n') }}"
      delegate_to: localhost
      when: fstab_before.stdout_lines != fstab_after.stdout_lines