---
- hosts: all

  vars:
    ansible_python_interpreter: auto_legacy_silent
    selinux_status_before: "/tmp/pkg_before_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    selinux_status_after: "/tmp/pkg_after_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    selinux_status_diff: "./reports/patched_packages_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"

  tasks:

    - name: Retrieve SELinux status before patching
      shell: sestatus
      register: sestatus_before
    
    - name: Create list of selinux status before patching
      copy:
        dest: "{{ selinux_status_before }}"
        content: "{{ sestatus_before.stdout_lines | join('\n') }}"
    
    - name: Patching servers
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Retrieve selinux status after patching
      shell: sestatus
      register: sestatus_after
    
    - name: Create list of selinux status after patching
      copy:
        dest: "{{ selinux_status_after }}"
        content: "{{ sestatus_after.stdout_lines | join('\n') }}"

    - name: Compare selinux status before and after patching
      shell: diff "{{ selinux_status_after }}" "{{ selinux_status_before }}" |
            grep -v "^---" |
            grep -v "^[0-9c0-9]"
      register: sestatus_diff
      changed_when: sestatus_diff != ""
      failed_when: false
    
    - name: Generate selinux status comparison list
      copy:
        dest: "{{ selinux_status_diff }}"
        content: "{{ sestatus_diff.stdout_lines | join('\n') }}"
      delegate_to: localhost
      when: sestatus_before.stdout_lines != sestatus_after.stdout_lines